In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
print(f"version of tensor flow : {tf.__version__}")
print(f"version of Keras : { tf.keras.__internal__ }")
print(f"Eager Execution is : {tf.executing_eagerly()}")

version of tensor flow : 2.15.0
version of Keras : <module 'keras.api._v2.keras.__internal__' from '/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/__internal__/__init__.py'>
Eager Execution is : True


In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_physical_devices('GPU')

[]

In [ ]:
if tf.test.is_gpu_available():
  print("Gpu is avaliable")
else :
  print("working on cpu")

working on cpu


In [ ]:
c = tf.constant(42)

In [ ]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
c.numpy()

42

In [ ]:
c.shape

TensorShape([])

In [ ]:
c.dtype

tf.int32

In [ ]:
c1 = tf.constant(4, dtype= "int64")

In [ ]:
c1

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
c1.dtype

tf.int64

In [ ]:
c1.numpy()

4

In [ ]:
c2 = tf.constant([[2,3],[3,4]])

In [ ]:
c2.dtype

tf.int32

In [ ]:
c2.shape

TensorShape([2, 2])

In [ ]:
c2.numpy()

array([[2, 3],
       [3, 4]], dtype=int32)

In [ ]:
c2[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
c2[0][0].numpy = 10

In [ ]:
c2.numpy()

array([[2, 3],
       [3, 4]], dtype=int32)

In [ ]:
c2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]], dtype=int32)>

In [ ]:
## like numpy constant zero and one

In [ ]:
o = tf.ones(shape=(1,1))

In [ ]:
o

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [ ]:
o.numpy()

array([[1.]], dtype=float32)

In [ ]:
one = tf.ones(shape=(2,3))

In [ ]:
one

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
one.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
type(one)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
one.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
type(one.numpy())

numpy.ndarray

In [ ]:
one[0][0].numpy()

1.0

In [ ]:
one[0][0].numpy() == 10

False

In [ ]:
one[0][0].numpy = 10

In [ ]:
one.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
zero = tf.zeros(shape=(3,3))

In [ ]:
zero.numpy()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
one.dtype

tf.float32

In [ ]:
zero.dtype

tf.float32

In [ ]:
import tensorflow as tf

In [ ]:
constant1 = tf.constant([[1,2,3],[4,5,6]])
constant2 = tf.constant([[1,2,3],[4,5,6]])

In [ ]:
constant1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
constant2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
addition = constant1 + constant2

In [ ]:
additionnn = tf.add(constant1, constant2)

In [ ]:
addition.numpy()

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [ ]:
additionnn.numpy()

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [ ]:
addition.dtype

tf.int32

In [ ]:
additionnn.dtype

tf.int32

In [ ]:
## random constant

In [ ]:
normal_data = tf.random.normal(shape=(2,2),mean=0,stddev=1)

In [ ]:
normal_data

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.13439186, -0.07760868],
       [ 0.205408  , -0.6752294 ]], dtype=float32)>

In [ ]:
normal_data.shape

TensorShape([2, 2])

In [ ]:
normal_data.numpy()

array([[-0.13439186, -0.07760868],
       [ 0.205408  , -0.6752294 ]], dtype=float32)

In [ ]:
uniform_data = tf.random.uniform(shape=(2,2), minval=0, maxval=10, dtype="int32")

In [ ]:
uniform_data

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 5],
       [9, 5]], dtype=int32)>

In [ ]:
uniform_data.numpy()

array([[7, 5],
       [9, 5]], dtype=int32)

In [ ]:
uniform_data.shape

TensorShape([2, 2])

In [ ]:
uniform_data.dtype

tf.int32

In [ ]:
# variable declare in tensor flow

In [ ]:
# In python

var0 = 42

In [ ]:
var0

42

In [ ]:
var1 = tf.Variable(32)
## rank 0 tensor

In [ ]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>

In [ ]:
var1.shape

TensorShape([])

In [ ]:
var1.dtype

tf.int32

In [ ]:
var1.numpy

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>>

In [ ]:
var2 = tf.Variable([[1,2,3,4],[2,3,4,5]])

#  rank 2 tensor

In [ ]:
var2

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5]], dtype=int32)>

In [ ]:
var2.dtype

tf.int32

In [ ]:
var2.numpy()

array([[1, 2, 3, 4],
       [2, 3, 4, 5]], dtype=int32)

In [ ]:
var3 = tf.Variable([[[1,2,3],[3,4,5]],[[1,2,3],[4,5,6]]], dtype ="float64")

In [ ]:
## rank 3 tensor
var3

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float64, numpy=
array([[[1., 2., 3.],
        [3., 4., 5.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])>

In [ ]:
var3.shape

TensorShape([2, 2, 3])

In [ ]:
var3.numpy()

array([[[1., 2., 3.],
        [3., 4., 5.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

In [ ]:
var3.dtype

tf.float64

In [ ]:
tf.rank(var3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
## re-assign

In [ ]:
var4 = tf.Variable(42)

In [ ]:
var4

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [ ]:
var4.assign(24)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=24>

In [ ]:
var4

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>

In [ ]:
var5 = tf.random.normal(shape=(2,2))

In [ ]:
var5

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8276751 , -0.58687323],
       [-0.61180955, -0.51304245]], dtype=float32)>

In [ ]:
a = tf.Variable(var5)

In [ ]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.8276751 , -0.58687323],
       [-0.61180955, -0.51304245]], dtype=float32)>

In [ ]:
a.assign(var5)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[-0.8276751 , -0.58687323],
       [-0.61180955, -0.51304245]], dtype=float32)>

In [ ]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.8276751 , -0.58687323],
       [-0.61180955, -0.51304245]], dtype=float32)>

In [ ]:
# Now we want to check it is assigned or not

In [ ]:
for i in range(2):
  for j in range(2):
    assert a[i,j] == var5[i,j]

In [ ]:
## assert give error if they are not same

In [ ]:
var5

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8276751 , -0.58687323],
       [-0.61180955, -0.51304245]], dtype=float32)>

In [ ]:
var6 = tf.random.normal(shape = (2,2))

In [ ]:
var6

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.9257628 , -0.19339262],
       [ 0.6107927 , -0.20257306]], dtype=float32)>

In [ ]:
a.assign_add(var6)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[ 0.45241058,  0.9915777 ],
       [-0.54290307, -1.9313821 ]], dtype=float32)>

In [ ]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.45241058,  0.9915777 ],
       [-0.54290307, -1.9313821 ]], dtype=float32)>

In [ ]:
var5 + var6

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.45241058,  0.9915777 ],
       [-0.54290307, -1.9313821 ]], dtype=float32)>

In [ ]:
## if we want to check

In [ ]:
for i in range(2):
  for j in range(2):
    assert a[i,j] == var5[i,j] + var6[i,j]

In [ ]:
a.numpy()

array([[ 0.45241058,  0.9915777 ],
       [-0.54290307, -1.9313821 ]], dtype=float32)

In [ ]:
# shaping tensor

In [ ]:
## reshape of tensor

In [ ]:
var1 = tf.Variable([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])

In [ ]:
var1.shape

TensorShape([2, 2, 3])

In [ ]:
var2 = tf.reshape(var1,[2,6])

In [ ]:
var2

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]], dtype=int32)>

In [ ]:
var3 = tf.reshape(var1,[1,12])

In [ ]:
var3

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9]], dtype=int32)>

In [ ]:
var3.shape

TensorShape([1, 12])

In [ ]:
var3.numpy()

array([[1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [ ]:
### ranking -- Dimention of an array

In [ ]:
var1 = tf.random.normal(shape=(2,2))
var1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.8034815 , -0.94624114],
       [ 0.2814052 ,  0.6604278 ]], dtype=float32)>

In [ ]:
tf.rank(var1)

## here numpy = 2

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
var2 = tf.Variable(42)

In [ ]:
tf.rank(var2)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
## here numpy = 0

In [ ]:
## sliceing

In [ ]:
var1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.8034815 , -0.94624114],
       [ 0.2814052 ,  0.6604278 ]], dtype=float32)>

In [ ]:
var1 = tf.Variable([[[2,3,4],[1,7,2]],[[6,7,8],[4,5,6]]])

In [ ]:
var1

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[2, 3, 4],
        [1, 7, 2]],

       [[6, 7, 8],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
var1.numpy()

array([[[2, 3, 4],
        [1, 7, 2]],

       [[6, 7, 8],
        [4, 5, 6]]], dtype=int32)

In [ ]:
var1.shape

TensorShape([2, 2, 3])

In [ ]:
var1.dtype

tf.int32

In [ ]:
v = var1[1,0,2]    ## slice,row,columns
                  ##     1 ,  0,  2
                  # Start from 0

In [ ]:
v

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
v.numpy()

8

In [ ]:
var1.numpy()

array([[[2, 3, 4],
        [1, 7, 2]],

       [[6, 7, 8],
        [4, 5, 6]]], dtype=int32)

In [ ]:
## cats to numpy

In [ ]:
v = var1.numpy()

In [ ]:
# Apply numpy opration

In [ ]:
v

array([[[2, 3, 4],
        [1, 7, 2]],

       [[6, 7, 8],
        [4, 5, 6]]], dtype=int32)

In [ ]:
len(v)

2

In [ ]:
v.shape

(2, 2, 3)

In [ ]:
v.size

12

In [ ]:
## finding the size of a tensor

In [ ]:
var1

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[2, 3, 4],
        [1, 7, 2]],

       [[6, 7, 8],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tf.size(var1)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
tf.size(var1).numpy()

12

In [ ]:
tensor_size = tf.size(var1).numpy()

In [ ]:
tensor_size

12

In [ ]:
## data type

In [ ]:
var1.dtype

tf.int32

In [ ]:
## mathematical opration

In [ ]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
a+b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.3291394 , 0.06089842],
       [1.9080706 , 0.6945113 ]], dtype=float32)>

In [ ]:
c = tf.square(a)
d = tf.exp(b)
e = tf.sqrt(c)

In [ ]:
print(c)
print(d)
print(e)

tf.Tensor(
[[0.15803853 0.24166514]
 [0.04791607 0.8053924 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.93388575 1.7375792 ]
 [5.4150014  0.81633925]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.3975406  0.4915945 ]
 [0.2188974  0.89743656]], shape=(2, 2), dtype=float32)


In [ ]:
print(a)
print(b)

tf.Tensor(
[[ 0.3975406  -0.4915945 ]
 [ 0.2188974   0.89743656]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.06840118  0.5524929 ]
 [ 1.6891731  -0.20292525]], shape=(2, 2), dtype=float32)


In [ ]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.3975406 , -0.4915945 ],
       [ 0.2188974 ,  0.89743656]], dtype=float32)>

In [ ]:
a*a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.15803853, 0.24166514],
       [0.04791607, 0.8053924 ]], dtype=float32)>

In [ ]:
a+a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.7950812, -0.983189 ],
       [ 0.4377948,  1.7948731]], dtype=float32)>

In [ ]:
a-a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
### broad casting

In [ ]:
var1 = tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
var1

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
var1.shape

TensorShape([2, 2, 3])

In [ ]:
var1.numpy()

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [ ]:
var4 = var1*4

In [ ]:
var4.numpy()

array([[[ 4,  8, 12],
        [16, 20, 24]],

       [[28, 32, 36],
        [40, 44, 48]]], dtype=int32)

In [ ]:
var4.shape

TensorShape([2, 2, 3])

In [ ]:
a = tf.random.normal(shape=(4,4),stddev=2,mean=0)
a.numpy()

array([[ 1.3672218 , -1.7618424 ,  2.8687055 , -1.0238514 ],
       [-1.81744   ,  0.6677477 ,  0.30481339, -1.2920862 ],
       [-2.8663793 , -0.4736754 ,  1.8402444 , -1.4004925 ],
       [-1.8065501 , -1.3120468 , -0.6899626 ,  0.04793322]],
      dtype=float32)

In [ ]:
b = tf.ones(shape=(1,4))
b.numpy()

array([[1., 1., 1., 1.]], dtype=float32)

In [ ]:
a+b

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 2.3672218 , -0.76184237,  3.8687055 , -0.02385139],
       [-0.81744003,  1.6677477 ,  1.3048134 , -0.29208624],
       [-1.8663793 ,  0.5263246 ,  2.8402443 , -0.40049255],
       [-0.80655015, -0.31204677,  0.31003737,  1.0479332 ]],
      dtype=float32)>

In [ ]:
a + tf.transpose(b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 2.3672218 , -0.76184237,  3.8687055 , -0.02385139],
       [-0.81744003,  1.6677477 ,  1.3048134 , -0.29208624],
       [-1.8663793 ,  0.5263246 ,  2.8402443 , -0.40049255],
       [-0.80655015, -0.31204677,  0.31003737,  1.0479332 ]],
      dtype=float32)>

In [ ]:
tf.transpose(b)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
## matrix multiplication

In [ ]:
var1 = tf.constant([[1,2,3]])
var1

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [ ]:
var2 = tf.constant([[2,3,4]])
var2

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 3, 4]], dtype=int32)>

In [ ]:
tf.transpose(var1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [ ]:
tf.matmul(var1,tf.transpose(var2))


<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[20]], dtype=int32)>

In [ ]:
# casting

In [ ]:
var1

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [ ]:
var1.dtype

tf.int32

In [ ]:
var2 = tf.cast(var1,dtype="float32")
var2

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [ ]:
var2.dtype

tf.float32

In [ ]:
# With truncating

In [ ]:
c = tf.constant(4.9)

In [ ]:
c

<tf.Tensor: shape=(), dtype=float32, numpy=4.9>

In [ ]:
j = tf.cast(c,dtype="int32")
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
##    4.9 -->  4

In [ ]:
## Ragged tensor

In [ ]:
import tensorflow as tf
ragged = tf.ragged.constant([[1,2,3,4],[],[2,3,4],[5,6],[7]])
ragged

<tf.RaggedTensor [[1, 2, 3, 4], [], [2, 3, 4], [5, 6], [7]]>

In [ ]:
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([7], shape=(1,), dtype=int32)


In [ ]:
var1 = tf.constant([[1,2,3,4],[],[2,3,4],[5,6],[7]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [ ]:
## this is why we use ragged tensor

In [ ]:
# mathematic oprations

In [ ]:
varx = [1,2,3,4]
vary = 3
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 1, 0, 1], dtype=int32)>

In [ ]:
# tf.reduce_mean(input_tensor, axis = none, keepdims= none, name = none)

In [ ]:
## define a number

var1 = tf.constant([[1,2],[3,4]])
var1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
(1+2+3+4)/4

2.5

In [ ]:
tf.reduce_mean(var1)

## if we pass int data then we get int ans only
## if we pass float then only we get float ans

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
### it find across all the axis
## axis = None

var1 = tf.constant([[1.,2.],[3.,4.]])
var1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
tf.reduce_mean(var1)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [ ]:
## find across columns

tf.reduce_mean(input_tensor= var1,axis=0)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [ ]:
(1+3)/2

2.0

In [ ]:
(2+4)/2

3.0

In [ ]:
tf.reduce_mean(input_tensor= var1,axis=0,keepdims=True)


<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2., 3.]], dtype=float32)>

In [ ]:
## find mean across row

In [ ]:
tf.reduce_mean(var1,axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [ ]:
var1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
(1+2)/2

1.5

In [ ]:
(3+4)/2

3.5

In [ ]:
tf.reduce_mean(var1,axis=1,keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.5],
       [3.5]], dtype=float32)>

In [ ]:
### generating random value

In [ ]:
## tf.random.normal(shape,mean,stddev,dtype,seed,name)

In [ ]:
var = tf.random.normal(shape=(3,2),mean=10,stddev=2,dtype=tf.float32,seed=None,name = None)
print(var)

tf.Tensor(
[[10.040968  11.180076 ]
 [ 8.187303   7.5841064]
 [ 8.7728405  7.9670963]], shape=(3, 2), dtype=float32)


In [ ]:
## tf.random.uniform()
## tf.random.uniform(shape,minval, maxval,dtype,seed,name)


In [ ]:
var = tf.random.uniform(shape=(2,3),minval=0,maxval=None,seed=None,name=None)
print(var)

tf.Tensor(
[[0.37399173 0.25805652 0.5884476 ]
 [0.19182825 0.9500873  0.71842766]], shape=(2, 3), dtype=float32)


In [ ]:
## seting a seed

In [ ]:
tf.random.set_seed(11)
var1 = tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)
var2 = tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)
print(var1)
print(var2)
## call for first time

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [ ]:
tf.random.set_seed(11)
var1 = tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)
var2 = tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)
print(var1)
print(var2)
## call for second time

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [ ]:
### Example
dice1 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
add_val = dice1+dice2
print(dice1)
print(dice2)
print(add_val)

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[5],
       [2],
       [4],
       [1],
       [3],
       [5],
       [6],
       [1],
       [2],
       [3]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[5],
       [2],
       [2],
       [4],
       [1],
       [5],
       [1],
       [3],
       [5],
       [6]], dtype=int32)>
tf.Tensor(
[[10]
 [ 4]
 [ 6]
 [ 5]
 [ 4]
 [10]
 [ 7]
 [ 4]
 [ 7]
 [ 9]], shape=(10, 1), dtype=int32)


In [ ]:
full_tensor = tf.concat(values=[dice1,dice2,add_val],,axis=1)
print(full_tensor)

tf.Tensor(
[[ 5  5 10]
 [ 2  2  4]
 [ 4  2  6]
 [ 1  4  5]
 [ 3  1  4]
 [ 5  5 10]
 [ 6  1  7]
 [ 1  3  4]
 [ 2  5  7]
 [ 3  6  9]], shape=(10, 3), dtype=int32)


In [ ]:
full_tensor.numpy()

array([[ 5,  5, 10],
       [ 2,  2,  4],
       [ 4,  2,  6],
       [ 1,  4,  5],
       [ 3,  1,  4],
       [ 5,  5, 10],
       [ 6,  1,  7],
       [ 1,  3,  4],
       [ 2,  5,  7],
       [ 3,  6,  9]], dtype=int32)

In [ ]:
## finding the largest and smallest value

In [ ]:
# tf.argmax(input,axis=None,name=None,output_type)
# tf.argmin(input,axis=None,name=None,output_type)


In [ ]:
var1 = tf.Variable([1,2,3,4,5,6,7,-1,-11,-3,-6,0],dtype=tf.int32)

In [ ]:
print(var1)

<tf.Variable 'Variable:0' shape=(12,) dtype=int32, numpy=
array([  1,   2,   3,   4,   5,   6,   7,  -1, -11,  -3,  -6,   0],
      dtype=int32)>


In [ ]:
max = tf.argmax(var1)

In [ ]:
max.numpy()
## it represent the index number

6

In [ ]:
var1[6].numpy()
## this is over maximum value in var1

7

In [ ]:
min = tf.argmin(var1,axis=0).numpy()
print(min)

8


In [ ]:
value = var1[min].numpy()
print(value)

-11


In [ ]:
var2 = tf.reshape(var1,[4,3])

In [ ]:
print(var2)

tf.Tensor(
[[  1   2   3]
 [  4   5   6]
 [  7  -1 -11]
 [ -3  -6   0]], shape=(4, 3), dtype=int32)


In [ ]:
min = tf.argmin(var2,axis=0)    ## row wise min    1,4,7,-3 min is -3
print(min)

tf.Tensor([3 3 2], shape=(3,), dtype=int64)


In [ ]:
max = tf.argmax(var2,axis=0)    ### row wise max   ## axis 0 min compare between row and give max and min
print(max)

tf.Tensor([2 1 1], shape=(3,), dtype=int64)


In [ ]:
min_columns = tf.argmin(var2,axis=1)
print(min_columns)

tf.Tensor([0 0 2 1], shape=(4,), dtype=int64)


In [ ]:
max_columns = tf.argmax(var2,axis=1)
print(max_columns)

tf.Tensor([2 2 0 2], shape=(4,), dtype=int64)


In [ ]:
var2

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,  -1, -11],
       [ -3,  -6,   0]], dtype=int32)>

In [ ]:
## axis = 1  it compare between columns and give min and max result

In [ ]:
## saving and restoring using check points

In [ ]:
variable = tf.Variable([[1,2,3,4],[2,3,4,5]])
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5]], dtype=int32)>


In [ ]:
check_point = tf.train.Checkpoint(var=variable)
check_point

In [ ]:
save_path =check_point.save('./vars')

In [ ]:
save_path

'./vars-1'

In [ ]:
variable.assign([[0,0,0,0],[0,0,0,0]])
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>


In [ ]:
check_point.restore(save_path)

In [ ]:
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5]], dtype=int32)>


In [ ]:
### tf.function

In [ ]:
import tensorflow as tf
## python function
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x**2,5)+(y**2))
## tensor flow function

f2 = tf.function(f1)


In [ ]:
X = tf.constant([4.,-5.])

In [ ]:
Y = tf.constant([2.,3.])


In [ ]:
f1(X,Y)

<tf.Tensor: shape=(), dtype=float32, numpy=109.0>

In [ ]:
f1(X,Y).numpy()

109.0

In [ ]:
f2(X,Y)

<tf.Tensor: shape=(), dtype=float32, numpy=109.0>

In [ ]:
f2(X,Y).numpy()

109.0

In [ ]:
## both give the same ans the diff is that f2 (tensorflow function execute as a tensorflow graph)

In [ ]:
## calculate gradient decent

In [ ]:
## gradient Tape

In [ ]:
## if we have constant then we have watch tensor.
## if we have variable then we don't need to watch the variable

In [ ]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
print(a)
print(b)

with tf.GradientTape() as tape:
  tape.watch(a)
  c = tf.sqrt(tf.square(a)+tf.square(b))
  print(c)
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-1.0801817  -0.8719295 ]
 [-0.07622255  0.16448632]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.9545673  0.7554583]
 [-1.8376459  1.2934046]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.2331874 1.1536803]
 [1.839226  1.3038218]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.48369506 -0.7557809 ]
 [-0.04144273  0.12615706]], shape=(2, 2), dtype=float32)


In [ ]:
# now suppose if we have a as a variable then we dont need to watch them

a = tf.Variable(a)

with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a)+tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.48369506 -0.7557809 ]
 [-0.04144273  0.12615706]], shape=(2, 2), dtype=float32)


In [ ]:
with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a)+tf.square(b))
  dc_db = tape.gradient(c,b)
  print(dc_db)


  ## because we are not watch b

None


In [ ]:
with tf.GradientTape() as tape:
  tape.watch(b)
  c = tf.sqrt(tf.square(a)+tf.square(b))
  dc_db = tape.gradient(c,b)
  print(dc_db)

tf.Tensor(
[[-0.8752366   0.6548246 ]
 [-0.99914086  0.9920103 ]], shape=(2, 2), dtype=float32)


In [ ]:
## if we convert it into a variable

b = tf.Variable(b)

with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_db = tape.gradient(c,b)
    print(dc_db)

tf.Tensor(
[[-0.8752366   0.6548246 ]
 [-0.99914086  0.9920103 ]], shape=(2, 2), dtype=float32)


In [ ]:
## this is a single derivation

In [ ]:
## Double derivation just apply nested loops

In [ ]:
with tf.GradientTape() as outer_tap:

    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
        print(dc_da)

    dc_da2 = outer_tap.gradient(dc_da,a)
print(dc_da2)

tf.Tensor(
[[-0.48369506 -0.7557809 ]
 [-0.04144273  0.12615706]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.34302497 0.371676  ]
 [0.5427731  0.7547691 ]], shape=(2, 2), dtype=float32)
